// Pjesët e përbashkëta (përmbledhja, udhëtimi, linja kohore), grafikat dhe prezantimi i udhëhequr.
export default {
  sq: {
    synthetic: 'Profil sintetik', private: 'Profil privat',
    snapSpoken: '{label}: {base}{unit} deri {recent}{unit}, ndryshim {pct}', crossed: 'kaloi pragun', diff: 'dallimi {d}', change: 'ndryshim',
    snapFooter: 'Bazuar në {n} ditët e fundit, krahasuar me normalen tënde. Për pesë matje shënohet rënia; për ngarkesën shënohet rritja — ky është i vetmi dallim, dhe është i njëjtë kudo në aplikacion.',
    jDone: 'regjistruar', jMissing: 'pa check-in', jPending: 'sot, ende pa check-in', jFuture: 'ende përpara',
    jSummary: '{done} ditë të regjistruara, {missing} pa check-in, {remaining} ende përpara, nga 30',
    timeline: '30 ditët e fundit. Përdor shigjetat për të lëvizur, Enter për të hapur një ditë.',
    dayRecorded: 'check-in i regjistruar', dayMissing: 'pa check-in', dayBaseline: 'pjesë e baseline-it', dayRecent: 'pjesë e 7 ditëve të fundit', dayToday: 'sot',
    dayDetails: 'Detajet e ditës', dayNone: 'Nuk ka check-in për këtë ditë. Dita nuk numërohet në asnjë mesatare.',
    noActivities: 'Pa aktivitete të shënuara', last7: '7 ditët e fundit', baseline: 'baseline', outside: 'jashtë periudhave',
    chartRecent: '{n} ditët e fundit', chartAvg: 'Mesatarja 7-ditore: {v}', chartNoAvg: 'ende pa 7 ditë', chartDays: '{n} ditë',
    mapLabel: 'Harta e lidhjeve mes gjashtë matjeve', noRelation: 'pa lidhje të shënuar',
    wallLabel: 'Connection Wall: ti në qendër dhe {n} {people} përreth', person: 'person', persons: 'persona', you: 'Ti',
    tourLabel: 'Prezantim i udhëhequr', tourStep: 'Hapi {n} nga {total} · {title}', tourPrev: 'Hapi i mëparshëm', tourNext: 'Hapi tjetër', tourClose: 'Mbyll prezantimin',
    tour: {
      data: { title: 'Profili sintetik', note: '30 ditë të gjeneruara nga kodi. Asnjë e dhënë e një personi të vërtetë.' },
      normal: { title: 'My Normal', note: 'Mesatarja jote nga 23 ditët bazë. Pika e krahasimit, jo një normë e përgjithshme.' },
      changed: { title: 'Something Changed', note: 'Katër nga gjashtë matjet lëvizën më shumë se zakonisht gjatë shtatë ditëve të fundit.' },
      why: { title: 'Why?', note: 'Cilat matje lëvizën bashkë. Shoqërim në të dhënat e tua, jo shkak.' },
      helps: { title: 'What Helps Me?', note: 'Aktivitetet e renditura sipas ditëve reale pas tyre, jo sipas sugjerimeve të përgjithshme.' },
      kafe: { title: 'Lidhjet · KAFE?', note: 'Një hap i vogël social. Sistemi përgatit draftin; dërgimin e bën vetë njeriu.' },
      wall: { title: 'Lidhjet · Wall', note: 'Njerëzit e zgjedhur vetë, pa pikë dhe pa renditje sipas rëndësisë.' },
      privacy: { title: 'Privatësia', note: 'Pa llogari asgjë nuk largohet nga pajisja. Llogaria opsionale ruan vetëm një kopje të enkriptuar në pajisje.' }
    }
  },
  en: {
    synthetic: 'Synthetic profile', private: 'Private profile',
    snapSpoken: '{label}: {base}{unit} to {recent}{unit}, change {pct}', crossed: 'crossed the threshold', diff: 'difference {d}', change: 'change',
    snapFooter: 'Based on the last {n} days, compared with your normal. For five measurements a fall is marked; for load a rise is marked — this is the only difference, and it is the same everywhere in the app.',
    jDone: 'recorded', jMissing: 'no check-in', jPending: 'today, no check-in yet', jFuture: 'still ahead',
    jSummary: '{done} days recorded, {missing} without check-in, {remaining} still ahead, out of 30',
    timeline: 'The last 30 days. Use the arrow keys to move, Enter to open a day.',
    dayRecorded: 'check-in recorded', dayMissing: 'no check-in', dayBaseline: 'part of the baseline', dayRecent: 'part of the last 7 days', dayToday: 'today',
    dayDetails: 'Day details', dayNone: 'There is no check-in for this day. The day is not counted in any average.',
    noActivities: 'No activities recorded', last7: 'last 7 days', baseline: 'baseline', outside: 'outside the periods',
    chartRecent: 'last {n} days', chartAvg: '7-day average: {v}', chartNoAvg: 'not 7 days yet', chartDays: '{n} days',
    mapLabel: 'Map of links between the six measurements', noRelation: 'no relationship recorded',
    wallLabel: 'Connection Wall: you in the centre and {n} {people} around', person: 'person', persons: 'people', you: 'You',
    tourLabel: 'Guided tour', tourStep: 'Step {n} of {total} · {title}', tourPrev: 'Previous step', tourNext: 'Next step', tourClose: 'Close the tour',
    tour: {
      data: { title: 'Synthetic profile', note: '30 days generated by the code. No data from a real person.' },
      normal: { title: 'My Normal', note: 'Your average from the 23 baseline days. A point of comparison, not a general norm.' },
      changed: { title: 'Something Changed', note: 'Four of the six measurements moved more than usual during the last seven days.' },
      why: { title: 'Why?', note: 'Which measurements moved together. Association in your data, not cause.' },
      helps: { title: 'What Helps Me?', note: 'Activities ranked by the real days after them, not by general advice.' },
      kafe: { title: 'Connections · KAFE?', note: 'A small social step. The app prepares the draft; the person sends it themselves.' },
      wall: { title: 'Connections · Wall', note: 'People chosen by you, with no points and no ranking by importance.' },
      privacy: { title: 'Privacy', note: 'Without an account nothing leaves the device. The optional account stores only a copy encrypted on the device.' }
    }
  }
};
