// Ekrani i pëlqimit: asgjë nuk shkruhet para se përdoruesi të zgjedhë.
export default {
  sq: {
    collected: [
      'Gjashtë numra në ditë: humori, gjumi, energjia, lidhja sociale, gëzimi dhe ngarkesa.',
      'Tags të aktiviteteve, p.sh. basketboll ose mësim. I zgjedh ti.',
      'Një shënim i shkurtër, vetëm nëse do ta shkruash.'
    ],
    why: [
      'Që të ndërtohet "My Normal" — mesatarja jote personale, jo një normë e përgjithshme.',
      'Që të vërehet kur patterni yt ndryshon krahasuar me ty vetë.',
      'Që të kesh ndihmë konkrete kur do të afrohesh me dikë që e ke zgjedhur vetë.'
    ],
    never: [
      'Nuk përdor kamerë dhe nuk lexon fytyra apo emocione.',
      'Nuk të vendos diagnozë dhe nuk emërton asnjë gjendje mjekësore. Raporton vetëm sa lëvizën numrat e tu.',
      'Nuk dërgon asnjë mesazh, email apo njoftim në vend tëndin.',
      'Nuk të krahason me persona të tjerë apo me ndonjë standard.',
      'Pa reklama dhe pa shitje të dhënash. Analitika anonime vetëm nëse e ndez vetë më vonë.',
      'Pa llogari, nuk i çon të dhënat askund — gjithçka rri në këtë pajisje. Llogaria është opsionale dhe ruan vetëm një kopje të enkriptuar në pajisje.'
    ],
    title: 'Patterni yt.<br>Vetëm i yti.',
    lede: 'Ky sistem mëson se si duket një javë e zakonshme për ty, dhe të tregon kur diçka ndryshon krahasuar me ty vetë — jo me askënd tjetër.',
    collectedTitle: 'Çfarë mblidhet', whyTitle: 'Pse mblidhet', whereTitle: 'Ku ruhet dhe çfarë nuk bën kurrë ky sistem',
    where: "Të dhënat ruhen vetëm në <strong>localStorage</strong> të këtij shfletuesi, nën një çelës të vetëm: <code>ajemire.v1</code>. Llogaria me email është opsionale dhe mund ta shtosh më vonë, vetëm nëse do kopje rezervë. Mund t'i eksportosh ose t'i fshish të gjitha në çdo moment.",
    store: 'Ruaj check-ins në këtë pajisje', storeHint: 'E domosdoshme. Pa këtë, aplikacioni nuk mban asgjë dhe nuk ka çfarë të krahasojë.',
    textHelp: 'Ndihmë opsionale për tekstin', textHelpHint: 'Reflektim javor dhe drafte mesazhesh, të ndërtuara nga template lokale në pajisje. Pa internet, pa API.',
    start: 'Si do të fillosh', demo: 'Shiko demon 30-ditore', demoHint: 'Profil sintetik i gjeneruar nga kodi. Jo i një personi të vërtetë.',
    private: 'Nis profil privat bosh', privateHint: 'Zero të dhëna. Baseline-i ndërtohet nga check-ins e tua.',
    nothingWritten: 'Asgjë nuk shkruhet në këtë pajisje derisa të shtypësh njërin nga dy butonat e mësipërm.'
  },
  en: {
    collected: [
      'Six numbers a day: mood, sleep, energy, social connection, joy and load.',
      'Activity tags, e.g. basketball or studying. You choose them.',
      'A short note, only if you want to write one.'
    ],
    why: [
      'To build "My Normal" — your personal average, not a general norm.',
      'To notice when your pattern changes compared with yourself.',
      'To give you concrete help when you want to reach out to someone you chose yourself.'
    ],
    never: [
      'It does not use a camera and does not read faces or emotions.',
      'It does not diagnose you and does not name any medical condition. It only reports how much your numbers moved.',
      'It does not send any message, email or notification on your behalf.',
      'It does not compare you with other people or with any standard.',
      'No advertising and no selling of data. Anonymous analytics only if you turn it on yourself later.',
      'Without an account, your data goes nowhere — everything stays on this device. The account is optional and only stores a copy encrypted on the device.'
    ],
    title: 'Your pattern.<br>Only yours.',
    lede: 'This app learns what an ordinary week looks like for you, and shows you when something changes compared with yourself — not with anyone else.',
    collectedTitle: 'What is collected', whyTitle: 'Why it is collected', whereTitle: 'Where it is stored and what this app never does',
    where: 'Data is stored only in this browser’s <strong>localStorage</strong>, under a single key: <code>ajemire.v1</code>. The email account is optional and you can add it later, only if you want a backup. You can export or delete everything at any time.',
    store: 'Store check-ins on this device', storeHint: 'Required. Without it, the app keeps nothing and has nothing to compare.',
    textHelp: 'Optional text help', textHelpHint: 'Weekly reflection and message drafts, built from local templates on the device. No internet, no API.',
    start: 'How do you want to start', demo: 'See the 30-day demo', demoHint: 'A synthetic profile generated by the code. Not a real person.',
    private: 'Start an empty private profile', privateHint: 'Zero data. The baseline is built from your check-ins.',
    nothingWritten: 'Nothing is written to this device until you press one of the two buttons above.'
  }
};
