// Ekrani MY 5: njerëz të zgjedhur me dorë, vetëm në pajisje. Asnjë njoftim, asnjë dërgim automatik.
export default {
  sq: {
    title: 'MY 5',
    subtitle: 'Deri në pesë persona që i zgjedh vetë. Shkruhen me dorë, ruhen vetëm këtu, dhe nuk renditen sipas rëndësisë.',
    count: '{n} nga {max}', add: 'Shto person', empty: 'Ende asnjë person',
    emptyText: 'Shto dikë që e ke zgjedhur vetë. Nuk kërkohet qasje te kontaktet e telefonit dhe asgjë nuk dërgohet.',
    demoNote: 'Këta tre janë profile demonstruese sintetike, të gjeneruara nga kodi. Nuk janë persona të vërtetë.',
    noNotify: 'Asnjë nga këta persona nuk merr njoftim. Sistemi vetëm përgatit një draft që e kopjon ti dhe e dërgon vetë, nga aplikacioni yt.',
    noDate: 'pa datë kontakti', today: 'sot', daysAgo: '{n} ditë më parë', defaultActivity: 'një kafe',
    edit: 'Ndrysho {name}', remove: 'Hiq {name}',
    name: 'Emri', relation: 'Lidhja', relationHint: 'p.sh. kushërirë, shok klase', activity: 'Aktiviteti i zakonshëm bashkë',
    lastContact: 'Kontakti i fundit', optional: 'opsionale', color: 'Ngjyra', colorOption: 'Ngjyra {c}',
    cancel: 'Anulo', save: 'Ruaj', addTitle: 'Shto person', editTitle: 'Ndrysho personin',
    nameEmpty: 'Emri nuk mund të jetë bosh', added: '{name} u shtua', updated: '{name} u përditësua',
    removeTitle: 'Hiq personin', removeText: 'Do të hiqet <strong>{name}</strong> nga MY 5. Historiku i lidhjeve mbetet.',
    removeButton: 'Hiqe', removed: '{name} u hoq'
  },
  en: {
    title: 'MY 5',
    subtitle: 'Up to five people you choose yourself. Typed by hand, stored only here, and not ranked by importance.',
    count: '{n} of {max}', add: 'Add person', empty: 'No one yet',
    emptyText: 'Add someone you chose yourself. No access to phone contacts is requested and nothing is sent.',
    demoNote: 'These three are synthetic demo profiles generated by the code. They are not real people.',
    noNotify: 'None of these people receive a notification. The app only prepares a draft that you copy and send yourself, from your own app.',
    noDate: 'no contact date', today: 'today', daysAgo: '{n} days ago', defaultActivity: 'a coffee',
    edit: 'Edit {name}', remove: 'Remove {name}',
    name: 'Name', relation: 'Relationship', relationHint: 'e.g. cousin, classmate', activity: 'Usual activity together',
    lastContact: 'Last contact', optional: 'optional', color: 'Colour', colorOption: 'Colour {c}',
    cancel: 'Cancel', save: 'Save', addTitle: 'Add person', editTitle: 'Edit person',
    nameEmpty: 'The name cannot be empty', added: '{name} was added', updated: '{name} was updated',
    removeTitle: 'Remove person', removeText: '<strong>{name}</strong> will be removed from MY 5. The connection history stays.',
    removeButton: 'Remove', removed: '{name} was removed'
  }
};
