-- Përfshin edhe 20260924050514 dhe 20260924050635.
drop function if exists public.purge_resolved_reports();
drop function if exists public.mod_revoke_sanction(bigint);
drop function if exists public.mod_list_sanctions();
drop function if exists public.mod_resolve_report(bigint, text, text);
drop function if exists public.mod_open_report(bigint);
drop function if exists public.mod_list_reports(text, bigint, integer);
drop function if exists public.report_content(text, text, text, text);
drop table if exists public.reports;
drop function if exists public.post_replies(uuid, timestamptz, integer);
drop function if exists public.community_feed(timestamptz, uuid, integer);
drop function if exists public.my_blocks();
drop function if exists public.unblock_user(uuid);
drop function if exists public.block_user(uuid);
drop function if exists public.delete_reply(uuid);
drop function if exists public.delete_post(uuid);
drop table if exists public.share_decisions;
drop table if exists public.reactions;
drop table if exists public.replies;
drop function if exists public.replies_guard();
drop table if exists public.posts;
drop function if exists public.posts_guard();
drop function if exists public.valid_shared_measure(jsonb);
drop table if exists public.public_profiles;
drop function if exists public.check_nickname();
drop function if exists public.nickname_key(text);
drop table if exists public.mutes;
drop function if exists public.blocked_between(uuid, uuid);
drop table if exists public.blocks;
