drop function if exists public.my_roles();
drop function if exists public.update_content_page(text, text, text, boolean);
drop function if exists public.set_pilot_access(text, boolean);
drop function if exists public.set_feature_flag(text, boolean, boolean, boolean, boolean, boolean);
drop function if exists public.set_role(text, public.app_role, boolean);
drop function if exists public.claim_owner();
drop function if exists public.lookup_user_by_email(text);
drop function if exists public.enforce_rate(bigint, integer, text);
drop table if exists public.content_pages;
drop function if exists public.is_sanctioned(uuid, text);
drop table if exists public.sanctions;
drop function if exists public.feature_enabled(text);
drop table if exists public.feature_flags;
drop function if exists public.has_pilot_access();
drop table if exists public.pilot_access;
drop function if exists public.audit(text, text, text, jsonb);
drop table if exists public.audit_events;
drop function if exists public.recently_authenticated(interval);
drop table if exists public.user_roles;
drop function if exists public.has_any_role(public.app_role[]);
drop function if exists public.has_role(public.app_role);
drop type if exists public.app_role;
drop table if exists public.app_config;
